name: Update Docker Tables

on: [pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-tables:
    name: Update Docker Tables
    runs-on: ubuntu-22.04
    steps:
      - id: checkout
        uses: actions/checkout@v3
        name: Checkout Repo
        with:
          ref: ${{ github.head_ref }}
      - id: make-bwagatk-alignment-table
        name: Make Docker Table for BWA/GATK Alignment Workflow
        run: |
          python .github/scripts/workflow_to_docker_table.py --output_file docs/dockers_bwagatk_alignment.md workflows/kfdrc_alignment_wf.cwl
      - id: make-gatk-cramtogvcf-table
        name: Make Docker Table for GATK CRAM to gVCF Workflow
        run: |
          python .github/scripts/workflow_to_docker_table.py --output_file docs/dockers_gatk_cramtogvcf.md workflows/kfdrc-gatk-haplotypecaller-wf.cwl
      - id: make-sentieon-alignment-table
        name: Make Docker Table for Sentieon Alignment Workflow
        run: |
          python .github/scripts/workflow_to_docker_table.py --output_file docs/dockers_sentieon_alignment.md workflows/kfdrc_sentieon_alignment_wf.cwl
      - id: make-sentieon-gvcf-table
        name: Make Docker Table for Sentieon gVCF Workflow
        run: |
          python .github/scripts/workflow_to_docker_table.py --output_file docs/dockers_sentieon_gvcf.md workflows/kfdrc_sentieon_gvcf_wf.cwl
      - id: cpr
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update docker table
          title: Update Production WF Docker Tables
          body: |
            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.

            Docker tables for production workflows now have most up-to-date and complete list of Dockers.
          delete-branch: true
          branch: ${{ github.head_ref }}-adjust-dockers
          labels: bix-dev
